version: 0.2

env:
  variables:
    S3_BUCKET: "duaneleem.com"
    BUILD_ENV: "prod"
            
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli@1.1.0
  build:
    commands:
      - echo Build started on `date`
      - ng build --${BUILD_ENV}
  post_build:
    commands:
      # Clear S3 bucket.
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo S3 bucket "duaneleem.com" is cleared.
      # Copy dist folder to S3 bucket "duaneleem.com"
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist*'