version: 0.2

env:
  variables:
    S3_BUCKET: "duaneleem"
    BUILD_ENV: "prod"
            
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli@1.1.0
  build:
    commands:
      - echo Build started on `date`
      - ng build --${BUILD_ENV}
artifacts:
  files:
    - 'dist/*'
  discard-paths: yes