version: 0.2

env:
  variables:
    S3_BUCKET: "duaneleem.s3-website-us-west-1.amazonaws.com"
    BUILD_ENV: "prod"
            
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - sudo apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo apt-get -y install npm
      - sudo ln -s /usr/bin/nodejs /usr/bin/node
      - npm install npm -g
      - npm install
      - npm install -g @angular/cli@1.1.0
  build:
    commands:
      - echo Build started on `date`
      - ng build --${BUILD_ENV}
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/*
  discard-paths: yes
  base-directory: 'dist*'